#!/bin/bash

echo "================================================"
echo "PUSH YOUR NEW CODE TO GITHUB"
echo "================================================"
echo ""
echo "Your new code is committed and ready to push!"
echo "We just need to authenticate with GitHub."
echo ""
echo "OPTION 1: Install GitHub CLI (Fastest)"
echo "================================================"
echo ""
echo "Run these commands:"
echo ""
echo "  brew install gh"
echo "  gh auth login"
echo "  git push origin main --force"
echo ""
echo "The --force will replace the old code with your new code."
echo ""
echo ""
echo "OPTION 2: Use Personal Access Token"
echo "================================================"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Give it a name like 'Oasis Deploy'"
echo "4. Check the 'repo' checkbox"
echo "5. Click 'Generate token'"
echo "6. Copy the token (starts with ghp_)"
echo ""
echo "Then run:"
echo ""
echo "  git push https://YOUR_TOKEN@github.com/Pcgodwin001/oasis-ai-community.git main --force"
echo ""
echo "Replace YOUR_TOKEN with the token you copied"
echo ""
echo ""
echo "AFTER PUSHING:"
echo "================================================"
echo ""
echo "1. Vercel will automatically detect the new code"
echo "2. It will rebuild and redeploy automatically"
echo "3. Add the 2 environment variables in Vercel"
echo "4. Your app will work!"
echo ""
